### ISSUE TITLE
rpm verify test will not yield result if rpm utility reporting more issues

### ISSUE THREAD

**Issue by navidshaikh** [navidshaikh/introspection#15]
While running the tooling on  docker.io/centos/postgresql container image, noticed the rpm verify script is not yielding any result but "error". Found that the regex written for parsing the output of `rpm -Va` is not able to parse the output of warnings displayed as part of this command output. Did not encounter such case earlier.

```
➜ docker run -ti docker.io/centos/postgresql bash
bash-4.2# rpm -Va
Unsatisfied dependencies for fakesystemd-1-16.el7.centos.noarch:
    systemd conflicts with (installed) fakesystemd-1-16.el7.centos.noarch
[..]
```

**Comment by dharmit** [comment]
lgtm!
